modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="strengthswordsmpmod"
version="1.2.2"
displayName="StrengthSwordSMPMod"
credits="The_WereF0X"
displayURL="https://mcreator.net"
authors="The_WereF0X"

[[dependencies.strengthswordsmpmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




